const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const { unique, normalize } = require('../ranking-utils');

const books = unique([{ book_id: '123', title: '名字', creation_status: 0 }, { bookId: '123' }, { bookId: '124', creationStatus: 1 }]);
assert.equal(books.length, 2);
assert.equal(books[0].status, 'Completed');
assert.equal(books[1].status, 'Ongoing');
assert.equal(normalize({ book_id: '123', cover_url: 'https://p3-novel-sign.byteimg.com/novel-pic/abc~tplv?secret=1' }, 4).thumb_url, 'https://p6-novel.byteimg.com/thumb/novel-pic/abc');
assert.equal(normalize({ book_id: '0' }), null);
assert.equal(normalize({ book_id: '123', title: '\uE400' }).book_name, '□');
assert.equal(normalize({ book_id: '123', abstract: 'valid' }).abstract_verified, true);
assert.equal(normalize({ book_id: '123', abstract_unverified: true }).abstract_verified, false);
const snapshot = JSON.parse(fs.readFileSync('data/ranking-snapshot.json'));
assert.equal(unique(snapshot.peak.books).length, 30);
assert(snapshot.editor.books.length > 0);
const html = fs.readFileSync('index.html', 'utf8');
new vm.Script(html.split('<script>')[1].split('</script>')[0]);
assert.equal((html.match(/value="app-\d+"/g) || []).length, 19);
console.log('PASS: ranking normalization, deduplication, status, covers, metadata flags, snapshots, 19 boards and HTML syntax');
